import type { Metadata } from "next";
import { Inter, Michroma, Sora } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sora",
});

const michroma = Michroma({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-michroma",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${sora.variable} ${michroma.variable} antialiased`}
    >
      <body>
      {/* <LenisProvider> */}
        {children}
      {/* </LenisProvider> */}
      </body>
    </html>
  );
}
